-- ============================================================================
-- contacts — outreach contacts for founder-seat cold outreach
-- ----------------------------------------------------------------------------
-- Run this ONCE in the Supabase SQL editor:
--   https://supabase.com/dashboard/project/dndefddhocxqczinfpfg/sql/new
--
-- Founder-only ops data. RLS is ENABLED with NO policies, which means the
-- anon key cannot read or write it at all — service-role only, the same
-- pattern as the `subscriptions` table. Do not add an anon policy: this
-- table holds named individuals' work email addresses.
--
-- Safe to re-run: every statement is guarded.
-- ============================================================================

create table if not exists public.contacts (
  id             bigint generated by default as identity primary key,
  hotel_id       bigint      not null references public.hotels (id) on delete cascade,
  full_name      text,
  job_title      text,
  email          text,
  email_verified boolean     not null default false,
  source         text,
  status         text        not null default 'ready',
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint contacts_status_check check (
    status in ('ready', 'drafted', 'sent', 'replied', 'unsubscribed', 'bounced')
  )
);

-- One row per person per hotel. Case-insensitive, so Sarah@hotel.com and
-- sarah@hotel.com cannot both be inserted — this is the guard that stops
-- anyone being emailed twice.
create unique index if not exists contacts_hotel_email_key
  on public.contacts (hotel_id, lower(email))
  where email is not null;

-- Working lookups: "who at this hotel?" and "what's still to send?"
create index if not exists contacts_hotel_id_idx on public.contacts (hotel_id);
create index if not exists contacts_status_idx    on public.contacts (status);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists contacts_set_updated_at on public.contacts;
create trigger contacts_set_updated_at
  before update on public.contacts
  for each row
  execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS: on, with no policies = service-role access only
-- ---------------------------------------------------------------------------
alter table public.contacts enable row level security;

comment on table  public.contacts          is 'Outreach contacts per hotel. Founder-only: RLS on, no policies, service-role access only.';
comment on column public.contacts.source   is 'Where the contact came from, e.g. Apollo, website, LinkedIn.';
comment on column public.contacts.status   is 'ready | drafted | sent | replied | unsubscribed | bounced';
comment on column public.contacts.email_verified is 'True once the address has been verified by the sourcing tool or a successful send.';

-- ---------------------------------------------------------------------------
-- Confirm it worked — should return one row: contacts, rowsecurity = true
-- ---------------------------------------------------------------------------
select tablename, rowsecurity
from pg_tables
where schemaname = 'public' and tablename = 'contacts';
